pool:
  vmImage: ubuntu-latest

steps:
  - script: yarn --frozen-lockfile
    displayName: Install dependencies

  - script: yarn lint
    displayName: Lint

  - script: yarn build
    displayName: Build
